/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package esame;

import java.awt.Frame;
import java.io.File;
import javax.swing.JButton;
import javax.swing.JTextField;

/**
 *
 * @author Davide
 */
public class AggiungiFile extends javax.swing.JDialog {
    
    private Frame parent=null;
    private File file=null;
    
    private Libreria lib;
    
    private int t;
   
    /**
     * Creates new form AggiungiFile2
     */
    public AggiungiFile(java.awt.Frame parent, boolean modal, int t, Libreria l) {
        super(parent, modal);
        initComponents();
        //setta variabili locali
        this.parent=parent;
        this.t=t;
        lib=l;
        this.Text4.setEnabled(false);
        this.jOk.setEnabled(false);
        jLabelErr3.setVisible(false);
        jLabelErr5.setVisible(false);
        jLabelErr7.setVisible(false);
        jLabelErr6.setVisible(false);

        switch(t){
            case 0: //video
                    this.Text7.setVisible(false);
                    this.jLabel7.setVisible(false);
                    this.Text6.setVisible(false);
                    this.jLabel6.setVisible(false);
                    break;
                    
            case 1: //brani musicali
                    this.Text7.setVisible(false);
                    this.jLabel7.setVisible(false);
                    break;
                
            case 2: //ebook
                    this.Text5.setVisible(false);
                    this.jLabel5.setVisible(false);
                    this.Text6.setVisible(false);
                    this.jLabel6.setVisible(false);
                    break;
        }
        
    }

    public void setFile(File file) {
        this.file = file;
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Text1 = new javax.swing.JTextField();
        Text2 = new javax.swing.JTextField();
        Text3 = new javax.swing.JTextField();
        Text4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jOk = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        Text5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Text6 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Text7 = new javax.swing.JTextField();
        jLabelErr3 = new javax.swing.JLabel();
        jLabelErr5 = new javax.swing.JLabel();
        jLabelErr7 = new javax.swing.JLabel();
        jLabelErr6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Titolo:");

        jLabel2.setText("Autore:");

        jLabel3.setText("Anno:");

        jLabel4.setText("Percorso:");

        Text1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ControlloCampi(evt);
            }
        });

        Text2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ControlloCampi(evt);
            }
        });

        Text3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ControlloCampi(evt);
            }
        });

        jButton1.setText("Sfoglia");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jOk.setText("Ok");
        jOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jOkActionPerformed(evt);
            }
        });

        jLabel5.setText("Durata:");

        Text5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ControlloCampi(evt);
            }
        });

        jLabel6.setText("F. Campionamento:");

        Text6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ControlloCampi(evt);
            }
        });

        jLabel7.setText("N. Pagine: ");

        Text7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ControlloCampi(evt);
            }
        });

        jLabelErr3.setForeground(new java.awt.Color(255, 0, 0));
        jLabelErr3.setText("* numero intero");

        jLabelErr5.setForeground(new java.awt.Color(255, 0, 0));
        jLabelErr5.setText("* numero");

        jLabelErr7.setForeground(new java.awt.Color(255, 0, 0));
        jLabelErr7.setText("* numero intero");

        jLabelErr6.setForeground(new java.awt.Color(255, 0, 0));
        jLabelErr6.setText("* numero intero");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(57, 57, 57))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(Text6, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jOk)
                                .addGap(27, 27, 27))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelErr6)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Text2)
                                    .addComponent(Text1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Text4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(111, 111, 111)
                                                .addComponent(Text7, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel7))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabelErr7))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Text3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelErr3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Text5, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelErr5)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Text1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(Text7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelErr7))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Text2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Text4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jButton1))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Text3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabelErr3))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jOk)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(Text5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelErr5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Text6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelErr6))
                            .addComponent(jLabel6))
                        .addGap(40, 40, 40))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**Metodo che crea un nuovo FileChooser, setta la Text corrispondente al percorso del file
     * e richiama un ControlloCampi.
     * 
     * @param evt 
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        FileChooser filec=new FileChooser(parent, true, this, t);
        filec.setVisible(true);
        if(file!=null)
        this.Text4.setText(file.getPath());
        
        ControlloCampi(null);
        
    }//GEN-LAST:event_jButton1ActionPerformed
    
    /**Metodo che gestisce il borrone OK.
     * In base al file che si sta inserendo, crea un oggetto corrispondente e lo aggiunge 
     * alla libreria.
     * 
     * @param evt 
     */
    private void jOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jOkActionPerformed
        // TODO add your handling code here:
        creaFile(t);
        this.dispose();
    }//GEN-LAST:event_jOkActionPerformed
    
    /** Metodo che permette di controllare i campi inseriti, e in caso di giusto inserimento abilita
     *  il bottone "OK":
     *  - controlla i campi comuni ai tre tipi di file (video, brani, ebook)
     *  - tramite lo switch controlla i campi specifici del tipo di file
     * 
     *  Nello specifico:
     *  . nei casi in cui il campo inserito sia o l'anno, o la durata, o il numero di pagine, o la
     *    frequenza di campionamento controlla che si inseriscano solo numeri
     *  . successivamente controlla che i campi comuni a tutti i tipi di file siano pieni, e  in quel
     *    entra dello switch case per controllare che anche i campi specifici siano stati inderiti
     *  . se tutti i campi sono inseriti correttamente allora abilita il bottone "OK", alrimenti rimane 
     *    enable(false).
     * 
     * @param evt 
     */
    private void ControlloCampi(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ControlloCampi
        // TODO add your handling code here:
        // il controllo evt != null serve perchè in jButton1ActionPerformed rchiamo la fun con null.
        if(evt != null && evt.getComponent()==Text3)
            controlloText(3);
        if(evt != null && evt.getComponent()==Text5)
            controlloText(5);
        if(evt != null && evt.getComponent()==Text6)
            controlloText(6);
        if(evt != null && evt.getComponent()==Text7)
            controlloText(7);
        if(!this.Text1.getText().isEmpty()&&!this.Text2.getText().isEmpty()&&!this.Text3.getText().isEmpty()
                &&!this.Text4.getText().isEmpty()){
            switch(t){
                case 0: if(!this.Text5.getText().isEmpty() && isNumero(Text5.getText())!=0 && isNumero(Text3.getText())==2)
                            this.jOk.setEnabled(true);
                        else
                            this.jOk.setEnabled(false);
                        break;
                case 1: if(!this.Text6.getText().isEmpty()&&!this.Text5.getText().isEmpty() 
                            && isNumero(Text5.getText())!=0 && isNumero(Text6.getText())==2 && isNumero(Text3.getText())==2)
                            this.jOk.setEnabled(true);
                        else
                            this.jOk.setEnabled(false);
                        break;
                case 2: if(!this.Text7.getText().isEmpty() && isNumero(Text3.getText())==2)
                            this.jOk.setEnabled(true);
                        else
                            this.jOk.setEnabled(false);
                        break;
                }
            }
        else
            this.jOk.setEnabled(false);
        
    }//GEN-LAST:event_ControlloCampi
  
    /**Metodo che controlla l' inserimento dei soli campi numerici.
     * Nel caso di sbagliato inserimento rende visibili le "label guida", che indicano 
     * all' utente dove e perchè ha sbagliato.
     * 
     * @param n 
     */
    private void controlloText(int n){
        switch(n){
            case 3: if(!Text3.getText().isEmpty() && isNumero(Text3.getText())!=2)
                        this.jLabelErr3.setVisible(true);
                    else
                        this.jLabelErr3.setVisible(false);
                    break;
            case 5: if(!Text5.getText().isEmpty() && isNumero(Text5.getText())==0)
                        this.jLabelErr5.setVisible(true);
                    else
                        this.jLabelErr5.setVisible(false);
                    break;
            case 6: if(!Text6.getText().isEmpty() && isNumero(Text6.getText())!=2)
                        this.jLabelErr6.setVisible(true);
                    else
                        this.jLabelErr6.setVisible(false);
                    break;
            case 7: if(!Text7.getText().isEmpty() && isNumero(Text7.getText())!=2)
                        this.jLabelErr7.setVisible(true);
                    else
                        this.jLabelErr7.setVisible(false);
                    break;
            default:break;
        }
    }
    
    /**Metodo che ritorna un numero intero indicante il tipo di dato del campo analizzato.
     * In particolare cerca di convertire il testo del campo analizzato in intero o altrimenti 
     * in float. Se non ci riesce, tramite try/catch ritorna il numero corrispondente. 
     * Prova quindi a convertire il testo in intero, se ci riesce allora a posto, ritorna 2, 
     * se non ci riesce allora ho ancora due casi: o è float o non è un numero.
     * Prova a convertire il testo in float, se ci riesce allora a posto, ritorna 1, altrimenti
     * ritorna 0.
     * 
     * @param str
     * @return 
     */
    private int isNumero(String str){
        float num1;
        float num2;
        try{
            num2=Integer.valueOf(str);
        }
        catch(NumberFormatException e){
            try{
                num1=Float.valueOf(str);
            }
            catch(NumberFormatException ex){
                return 0;
            }
            return 1;
        }
        return 2;
    }

    public File getFile() {
        return file;
    }

    public Libreria getLib() {
        return lib;
    }

    public int getT() {
        return t;
    }

    public JTextField getText1() {
        return Text1;
    }

    public JTextField getText2() {
        return Text2;
    }

    public JTextField getText3() {
        return Text3;
    }

    public JTextField getText4() {
        return Text4;
    }

    public JTextField getText5() {
        return Text5;
    }

    public JTextField getText6() {
        return Text6;
    }

    public JTextField getText7() {
        return Text7;
    }
    
    /* Metodo che costruisce il file multimediale e lo allega alla libreria    
    */
    public void creaFile(int x){
        switch(x){
            case 0: Video v=new Video(Float.valueOf(Text5.getText()), Text1.getText(), Text2.getText(),
                                        Integer.valueOf(Text3.getText()), file);
                    lib.aggiungiVideo(v);
                    break;
            case 1: BraniMusicali b=new BraniMusicali(Float.valueOf(Text5.getText()), Integer.valueOf(Text6.getText()),
                                        Text1.getText(),Text2.getText(), Integer.valueOf(Text3.getText()), file);
                    lib.aggiungiBranoMusicale(b);
                    break;
            case 2: Ebook e=new Ebook(Integer.valueOf(Text7.getText()), Text1.getText(), Text2.getText(),
                                        Integer.valueOf(Text3.getText()), file);
                    lib.aggiungiEbook(e);
                    break;
            default:
                    break;
        }
        
    }

    public JButton getjOk() {
        return jOk;
    }

    public void setText1(String Text1) {
        this.Text1.setText(Text1);
    }

    public void setText2 (String Text2) {
        this.Text2.setText(Text2);
    }

    public void setText3(String Text3) {
        this.Text3.setText(Text3);
    }

    public void setText4(String Text4) {
        this.Text4.setText(Text4);
    }

    public void setText5(String Text5) {
        this.Text5.setText(Text5);
    }

    public void setText6(String Text6) {
        this.Text6.setText(Text6);
    }

    public void setText7(String Text7) {
        this.Text7.setText(Text7);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Text1;
    private javax.swing.JTextField Text2;
    private javax.swing.JTextField Text3;
    private javax.swing.JTextField Text4;
    private javax.swing.JTextField Text5;
    private javax.swing.JTextField Text6;
    private javax.swing.JTextField Text7;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelErr3;
    private javax.swing.JLabel jLabelErr5;
    private javax.swing.JLabel jLabelErr6;
    private javax.swing.JLabel jLabelErr7;
    public javax.swing.JButton jOk;
    // End of variables declaration//GEN-END:variables
}
