/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package esame;

import javax.sound.sampled.*;
import java.io.File;
import java.io.IOException;

/**
 *
 * @author Davide
 */

class DialogRiproduci extends javax.swing.JDialog {
private AudioInputStream din;
private SourceDataLine line;
private volatile boolean paused;
private Object lock;

/**
     * Creates new form RiproduciBrani
     */
    public DialogRiproduci(java.awt.Frame parent, boolean modal, Libreria lib, int riga) {
        super(parent, modal);
        initComponents();
        this.setVisible(true);
        
        
        din = null;
        lock = new Object();
        paused = false;
        /*char [] s;
        char [] sottos=null;
        */

        try {
            AudioInputStream in = AudioSystem.getAudioInputStream(lib.ottieniElemento(riga).getPercorso());
            AudioFormat baseFormat = in.getFormat();
            AudioFormat decodedFormat = new AudioFormat(AudioFormat.Encoding.PCM_SIGNED,
                                    baseFormat.getSampleRate(), 16, baseFormat.getChannels(),
                                    baseFormat.getChannels() * 2, baseFormat.getSampleRate(),false);
            
            din = AudioSystem.getAudioInputStream(decodedFormat, in);
            DataLine.Info info = new DataLine.Info(SourceDataLine.class, decodedFormat);
            line = (SourceDataLine) AudioSystem.getLine(info);
            
            if(line != null) {
                line.open(decodedFormat);
                byte[] data = new byte[4096];
                // Start
                line.start();

                int nBytesRead;
                synchronized (lock) {
                    while ((nBytesRead = din.read(data, 0, data.length)) != -1) {
                        while (paused) {
                            if(line.isRunning()) {
                                line.stop();
                                }
                            try {
                                lock.wait();
                            }
                            catch(InterruptedException e) {
                            }
                        }

                        if(!line.isRunning()) {
                            line.start();
                        }
                    line.write(data, 0, nBytesRead);
                    }
                }

                // Stop
                line.drain();
                line.stop();
                line.close();
                din.close();
            }

        }
        catch(Exception e) {
            e.printStackTrace();
        }
        finally {
            if(din != null) {
                try { din.close(); } catch(IOException e) { }
            }
        }

    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jButton1.setText("Pause");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userPressedPause(evt);
            }
        });

        jButton2.setText("Play");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userPressedPlay(evt);
            }
        });

        jButton3.setText("Stop");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userPressedStop(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jButton1)
                .addGap(43, 43, 43)
                .addComponent(jButton2)
                .addGap(54, 54, 54)
                .addComponent(jButton3)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void userPressedPause(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userPressedPause
        // TODO add your handling code here:
        paused = true;
    }//GEN-LAST:event_userPressedPause

    private void userPressedPlay(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userPressedPlay
        // TODO add your handling code here:
        if(paused){
            synchronized(lock) {
                paused = false;
                lock.notifyAll();
            }
        }
    }//GEN-LAST:event_userPressedPlay

    private void userPressedStop(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userPressedStop
        // TODO add your handling code here:
        try {
            System.out.println("ho fatto tutto 0?");
            paused=true;
            line.drain();
            System.out.println("ho fatto tutto 1?");
            line.stop();
            System.out.println("ho fatto tutto 2?");
            line.close();
            System.out.println("ho fatto tutto 3?");
            din.close();
            System.out.println("ho fatto tutto 4?");
        }
        catch(Exception e) {
            e.printStackTrace();
            System.out.println(e.toString());
        }
        try { din.close(); } catch(IOException e2) {System.out.println(e2.toString()); }
        this.dispose();
    }//GEN-LAST:event_userPressedStop

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    // End of variables declaration//GEN-END:variables

}

