/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package esame;

import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Davide
 */
public class FileChooser extends javax.swing.JDialog {
    private AggiungiFile Afile;
    private int tipo;
    private FileNameExtensionFilter filtro;
    
    /**Costruttore che prendendo in ingresso il riferimento al file e al tipo, mi permette
     * di effettuare la scelta del file filtrandomela per tipo.
     * 
     * Creates new form FileChooser
     */
    public FileChooser(java.awt.Frame parent, boolean modal, AggiungiFile p, int t) {
        super(parent, modal);
        Afile=p;
        this.tipo=t;
        initComponents();
        //setDialogTitle(String dialogTitle)
        switch(t){
            case 0: filtro=new FileNameExtensionFilter("file video supportati", "avi");
                    break;
            case 1: filtro=new FileNameExtensionFilter("file audio supportati", "mp3");
                    break;
            case 2: filtro=new FileNameExtensionFilter("file ebook supportati", "pdf");
                    break;
        }
        JFileChooser.setFileFilter(filtro);
        JFileChooser.setAcceptAllFileFilterUsed(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JFileChooser = new javax.swing.JFileChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        JFileChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JFileChooserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JFileChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JFileChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**Metodo che setta il file ottenuto dalla finestra FileChooser e mi chiude la dialog.
     * 
     * @param evt 
     */
    private void JFileChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JFileChooserActionPerformed
        // TODO add your handling code here:
        Afile.setFile(JFileChooser.getSelectedFile());
        this.dispose();
    }//GEN-LAST:event_JFileChooserActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser JFileChooser;
    // End of variables declaration//GEN-END:variables
}
