/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package esame;

import java.awt.Component;
import java.awt.Dialog;
import java.awt.print.PrinterException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.plaf.metal.MetalIconFactory;


/**
 *
 * @author Davide
 */
public class MyFrame extends JFrame {

    private TableModel t;
    private Libreria lib;
    private Component comp;
    
    private int rowcerca;
    private int colcerca;
    private String cercapar="";
    private boolean trovatocerca=false;
    private boolean trovris=false;
    
    public MyFrame(){
        this("");
    }

    
    /**
     * Creates new form MyFrame
     * @param titolo
     */
    public MyFrame(String titolo) {
        initComponents();
        //super(titolo);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        //BraniMusicali b=new BraniMusicali((float) 3.2343, 4, "ciao", "io", 1999, "zfdgaersg");
        t=new TableModel();
        Panel.setVisible(true);
        lib=new Libreria();
        Table1.setColumnSelectionAllowed(true);
        Table1.setModel(t);
        Table1.setVisible(true);
        jMenuItem8.setEnabled(false);
        jMenuItem5.setEnabled(false);
        jMenuItem10.setEnabled(false);
    }
            
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        Panel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Table1 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem9.setText("jMenuItem9");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Table1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        Table1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Table1);

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });

        jButton1.setText("Cerca");
        jButton1.setEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelLayout = new javax.swing.GroupLayout(Panel);
        Panel.setLayout(PanelLayout);
        PanelLayout.setHorizontalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelLayout.setVerticalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
            .addGroup(PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu1.setText("File");

        jMenuItem6.setText("Salva");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem6);

        jMenuItem7.setText("Carica");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem7);

        jMenuItem11.setText("Stampa");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem11);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        jMenu3.setText("Aggiungi");

        jMenuItem2.setText("Video");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuItem3.setText("Brani musicali");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuItem4.setText("Ebook");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenu2.add(jMenu3);

        jMenuItem8.setText("Modifica");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem8);

        jMenuItem5.setText("Elimina");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("Visuaizza");

        jMenuItem10.setText("Lancia");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem10);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**Metodo che permette di aggiungere un video alla libreria multimediale.
     * 
     * @param evt 
     */
    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        AggiungiFile d=new AggiungiFile(this, true, 0, lib);
        d.setVisible(true);
        t=new TableModel(lib);
        Table1.setModel(t);
        Table1.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**Metodo che permette di aggiungere un brano musicale alla libreria multimediale.
     * 
     * @param evt 
     */
    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        AggiungiFile d=new AggiungiFile(this, true, 1, lib);
        d.setVisible(true);
        t=new TableModel(lib);
        Table1.setModel(t);
        Table1.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**Metodo che permette di aggiungere un ebook alla libreria multimediale.
     * 
     * @param evt 
     */
    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        AggiungiFile d=new AggiungiFile(this, true, 2, lib);
        d.setVisible(true);
        t=new TableModel(lib);
        Table1.setModel(t);
        Table1.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        int riga;
        ModificaFile mf = null;
        riga=Table1.getSelectedRow();
        
        if(!Table1.getValueAt(riga, 5).toString().isEmpty())
            mf=new ModificaFile(this, true, 1, lib, riga);
        else if(!Table1.getValueAt(riga, 6).toString().isEmpty())
            mf=new ModificaFile(this, true, 2, lib, riga);
        else
            mf=new ModificaFile(this, true, 0, lib, riga);
        
        t=new TableModel(lib);
        Table1.setModel(t);
        Table1.setVisible(true);
        jMenuItem5.setEnabled(false);
        jMenuItem8.setEnabled(false);
        jMenuItem10.setEnabled(false);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void Table1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table1MouseClicked
        // TODO add your handling code here:
        jMenuItem8.setEnabled(true);
        jMenuItem5.setEnabled(true);
        jMenuItem10.setEnabled(true);
    }//GEN-LAST:event_Table1MouseClicked

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        lib.cancellaElemento(Table1.getSelectedRow());
        t=new TableModel();
        Panel.setVisible(true);
        lib=new Libreria();
        
        Table1.setModel(t);
        Table1.setVisible(true);
        jMenuItem5.setEnabled(false);
        jMenuItem8.setEnabled(false);
        jMenuItem10.setEnabled(false);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
       DialogSalva ds=new DialogSalva(this, true, lib);
       
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        
        DialogCarica dc= new DialogCarica(this, true, lib);
        dc.setVisible(true);
        t=new TableModel(lib);
        Table1.setModel(t);
        Table1.setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
        int riga;
        riga=Table1.getSelectedRow();
        MyThread mt=null;
        if(!Table1.getValueAt(riga, 5).toString().isEmpty()){
            mt=new MyThread(this, lib, riga);
            mt.start();
            
        }
        else{
            try{
                java.awt.Desktop.getDesktop().open(lib.ottieniElemento(riga).getPercorso());
                }
            catch(IOException e){
                System.out.println("ERRORE: software o percorso non trovato!");
                DialogErrore der= new DialogErrore(this, true, "software o percorso non trovato!");
                der.setVisible(true);
                };
        }
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Libreria libric=new Libreria();
        InfoBase o=new InfoBase();
        if(!cercapar.equals(jTextField1.getText())){
            System.err.println("entrato "+cercapar+"  "+jTextField1.getText());
            rowcerca=0;
            colcerca=-1;
            cercapar=jTextField1.getText();
            trovris=false;
        }
        
        cercaStringa();
        if(!trovatocerca && !trovris ){
            DialogErrore de=new DialogErrore(this, true, "Nessuna corrispondenza trovata");
            de.setVisible(true);
            jTextField1.setText("");
            cercapar="";
            jButton1.setEnabled(false);
        }
        else if(!trovatocerca && trovris){
            DialogStampaRicerca de=new DialogStampaRicerca(this, true, "Ricerca terminata",libric);
            de.setVisible(true);
            jTextField1.setText("");
            cercapar="";
            jButton1.setEnabled(false);
        }
        else{
            //ricavo l'elemento
            if(!t.getValueAt(rowcerca, 6).toString().isEmpty()){
                if(libric.getLunghezza()!=0 && !libric.ottieniElemento(libric.getLunghezza()-1).equals(
                                                    lib.ottieniElemento(rowcerca))){
                    o=new Ebook();
                    o=lib.ottieniElemento(rowcerca);
                    libric.aggiungiEbook((Ebook) o);
                }      
            }
            else if(!t.getValueAt(rowcerca, 5).toString().isEmpty()){
                if(libric.getLunghezza()!=0 && !libric.ottieniElemento(libric.getLunghezza()-1).equals(
                                                    lib.ottieniElemento(rowcerca))){
                    o=new BraniMusicali();
                    o=lib.ottieniElemento(rowcerca);
                    libric.aggiungiBranoMusicale((BraniMusicali) (o));
                }
                
            }
            else{
                if(libric.getLunghezza()!=0 && !libric.ottieniElemento(libric.getLunghezza()-1).equals(
                                                    lib.ottieniElemento(rowcerca))){
                    o=new Video();
                    o=lib.ottieniElemento(rowcerca);
                    libric.aggiungiVideo((Video) o);
                }
                
            }
            
            Table1.changeSelection(rowcerca, colcerca, false, false);
            System.out.println("row"+rowcerca+" col"+colcerca);
            trovatocerca=false;
            trovris=true;
            
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        // TODO add your handling code here:
        if(jTextField1.getText().isEmpty())
            jButton1.setEnabled(false);
        else
            jButton1.setEnabled(true);
    }//GEN-LAST:event_jTextField1KeyReleased

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        try {
            // TODO add your handling code here:
            Table1.print();
        } catch (PrinterException ex) {
            DialogErrore dg=new DialogErrore(this, true, "Impossibile stampare");
            dg.setVisible(true);
        }
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void cercaStringa(){
        while(!trovatocerca && rowcerca<lib.getLunghezza()){
            if(colcerca<6){
                colcerca++;
                System.err.println("sono incrrementato");
            }
            else{
                rowcerca++;
                colcerca=0;
            }
            
            //controllo ogni campo
            
            if(rowcerca<lib.getLunghezza() && t.getValueAt(rowcerca, colcerca).toString().contains(cercapar)){
                trovatocerca=true;
       
            }
            
                
                        
        }
        
    }
    public void setLibreria(Libreria l){
        lib=l;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel;
    private javax.swing.JTable Table1;
    private javax.swing.JButton jButton1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
